#!/usr/bin/env bash

set -euo pipefail

say() {
  printf "setup-simplex: %s\n" "$1"
}

err() {
  say "$1" >&2
  exit 1
}

main() {
  # Parse and validate arguments
  COMMIT_SHA="${1:-}"
  OWNER_REPO="${2:-}"
  FETCH_REF="${COMMIT_SHA:-master}"
  FILE_PATH="simplexup/install"

  if [ "$#" -lt 2 ]; then
    err "Usage: setup-simplex <revision> <owner_repo>"
  fi

  if [ -z "$OWNER_REPO" ]; then
    err "no OWNER_REPO variable set"
  fi

  # Download and execute the initial install script
  RAW_URL="https://raw.githubusercontent.com/${OWNER_REPO}/${FETCH_REF}/${FILE_PATH}"
  say "Fetching ${FILE_PATH} from ${RAW_URL}"

  curl -fsSL --retry 5 --retry-all-errors --retry-delay 2 "${RAW_URL}" | bash

  # Download the simplexup executable
  FILE_PATH="simplexup/simplexup"
  RAW_URL="https://raw.githubusercontent.com/${OWNER_REPO}/${FETCH_REF}/${FILE_PATH}"

  BASE_DIR="${XDG_CONFIG_HOME:-$HOME}"
  SIMPLEX_DIR="${SIMPLEX_DIR:-$BASE_DIR/.simplex}"
  SIMPLEX_BIN_DIR="$SIMPLEX_DIR/bin"
  BIN_PATH="$SIMPLEX_BIN_DIR/simplexup"

  # Ensure bin directory exists and download simplexup into it
  mkdir -p "$SIMPLEX_BIN_DIR"
  say "Fetching ${FILE_PATH} from ${RAW_URL}"

  curl -fsSL --retry 5 --retry-all-errors --retry-delay 2 "${RAW_URL}" -o "$BIN_PATH"
  chmod +x "$BIN_PATH"

  # Execute simplexup, using a specific commit if provided (and not master's default release)
  if [ "$FETCH_REF" != "master" ]; then
      say "Using simplexup and simplex from commit: ${FETCH_REF}"
      "$BIN_PATH" --commit "${FETCH_REF}"
  else
      say "Using simplexup from master branch and installing latest simplex"
      "$BIN_PATH"
  fi

  # Add the Simplex binary directory to GitHub Actions PATH
  echo "$SIMPLEX_BIN_DIR" >> "$GITHUB_PATH"

  # Verify installation
  say "Verifying simplex installation..."
  "${SIMPLEX_BIN_DIR}/simplex" --version
}

main "$@"
