# DEFAULT CONFIG 

# [build]
# src_dir = "./simf"
# simf_files = ["*.simf"]
# out_dir = "./src/artifacts"

# [regtest]
# mnemonic = "exist carry drive collect lend cereal occur much tiger just involve mean"
# rpc_port = 18443
# esplora_port = 3000
# rpc_user = "user"
# rpc_password = "password"

# [test]
# mnemonic = "exist carry drive collect lend cereal occur much tiger just involve mean"
# verbosity = "3"

# [test.esplora]
# url = "<esplora url>"
# network = "<Liquid, LiquidTestnet, ElementsRegtest>"

# [test.rpc]
# url = "<rpc url>"
# username = "<rpc username>"
# password = "<rpc password>"
